### ISSUE TITLE
Deciphers all encrypted text to the same text result 

### ISSUE THREAD

**Issue by frusty-the-snowman** [ichantzaras/creamcrackerz#1]
I think you might need to explain what you are or were trying to attempted as it seems that no matter what encrypted text you have you will always get the same out deciphered out put..

Chosen key length: 8
Encrypted data 
OBKRUOXOGHULBSOLIFBBWFLRVQQPRNGKSSOTWTQSJQSSEKZZWATJKLUDIAWINFBNYPVTTMZFPKWGDKZXTJCDIGKUHUAUEKCAR   

Restored key: POLITICS
Plaintext: ALTHOUGHJANEISNOTPARTICULARLYIMPRESSEDWITHJORDANSWORKRANKINGHIMBELOWSOMEOFHEROTHERREPORTSSHEDOESNOTWANTCONFLICTSOSHEDECIDESTOGRANTJORDANWHATHEREQUESTSANDKEEPHIMHAPPYUNSURPRISINGLYJORDANSCOLLEAGUESREGARDHIMASMANIPULATIVEANDPUSHYBUTTHEYDECIDETONOTRAISETHEISSUEINTHEHOPETHATJANEAPPRECIATESTHEIRATTITUDEANDTHATTHEIRACHIEVEMENTSSPEAKFORTHEMSELVESSADLYTHEIRSTRATEGYISFARLESSEFFECTIVETHANJORDANSWHICHCAUSESMOREOFJANESREPORTSTOBULLYHERINTOAPROMOTIO
I found the exact phrase on  this web site ...
https://hbr.org/2017/10/how-office-politics-corrupt-the-search-for-high-potential-employees

**Comment by ichantzaras** [comment]
Since it reads the same file located at encrypted/hostiletext.txt it will produce the same output....the output (key, plaintext) is the proof it works.
If you need to decrypt another file/ciphertext provide it as input to the `decypher ` function of `attack.py` file.
